# Generated by Django 5.1.7 on 2025-03-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_likes_alter_like_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='news',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AddField(
            model_name='news',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
